extends Node

signal objective_completed(objective: FieldObjectiveBase);
signal enter_combination_objective_available(objective: EnterCombinationObjective);
signal enter_combination_objective_unavailable(objective: EnterCombinationObjective);
signal mission_timer_checkpoint_reached()
